from pathlib import Path

readme = (
    "# Landmark Classifier CNN\n\n"
    "> UCB MSc Data Science and AI - Deep Learning Project 5\n"
    "> Guillermo Carvajal Vaca - 2026\n\n"
    "## Overview\n\n"
    "Automatic landmark classification using CNNs in PyTorch.\n"
    "Infers geographic location from images without GPS metadata.\n\n"
    "| Phase | Approach | Target |\n"
    "|---|---|---|\n"
    "| Phase 2 | CNN from Scratch (5 conv + BN + GAP) | Test Accuracy >= 40% |\n"
    "| Phase 3 | Transfer Learning (ResNet18 / ResNet50) | Test Accuracy >= 70% |\n"
    "| Phase 4 | TorchScript inference app | predict_landmarks(img_path, k) |\n\n"
    "## Dataset\n\n"
    "Subset of Google Landmarks Dataset v2 - 50 classes.\n"
    "Provided by UCB instructor. Not included in this repository.\n\n"
    "Place at:\n\n"
    "    G:/My Drive/Maestria Ciencia de Datos/DEEP_LEARNING/PROJECT_01/landmark_images/\n"
    "        train/  <- one subfolder per class\n"
    "        test/   <- same structure\n\n"
    "## Installation\n\n"
    "    git clone https://github.com/guillermocarvajalvaca-dev/landmark-classifier.git\n"
    "    cd landmark-classifier\n"
    "    python -m venv .venv\n"
    "    .venv/Scripts/Activate.ps1\n"
    "    pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121\n"
    "    pip install -r requirements.txt\n"
    "    python src/config.py\n\n"
    "Expected: DEVICE: cuda | TRAIN_DIR exists=True | TEST_DIR exists=True\n\n"
    "## Execution\n\n"
    "| Node | Role | Notebooks |\n"
    "|---|---|---|\n"
    "| PyCharm Local | src/ development, EDA, inference | 01, 04 |\n"
    "| Google Colab T4 | Heavy training (>=30 epochs) | 02, 03 |\n\n"
    "## Inference\n\n"
    "    from src.predictor import predict_landmarks\n"
    "    predictions = predict_landmarks('my_photo.jpg', k=3)\n"
    "    # [('Eiffel_Tower', 0.87), ('Arc_de_Triomphe', 0.09), ('Notre_Dame', 0.04)]\n\n"
    "## Visualization\n\n"
    "BI-grade curves via plotnine with UCB palette:\n"
    "- UCB Blue #003262 - primary series\n"
    "- UCB Gold #FDB515 - optimal checkpoint\n"
    "- UCB Dark Gold #C4820E - overfitting onset\n\n"
    "Each run generates: narrative PNG + BI confusion matrix + Executive Report MD.\n\n"
    "## Results\n\n"
    "| Experiment | Type | Test Accuracy |\n"
    "|---|---|---|\n"
    "| E1_scratch_baseline | CNN Scratch | fill after training |\n"
    "| E2_scratch_augmented | CNN Scratch | fill after training |\n"
    "| E3_scratch_lower_lr | CNN Scratch | fill after training |\n"
    "| E4_resnet18_frozen | Transfer Learning | fill after training |\n"
    "| E5_resnet18_finetune_layer4 | Transfer Learning | fill after training |\n"
    "| E6_resnet50_frozen | Transfer Learning | fill after training |\n\n"
    "## Video\n\n"
    "YouTube: https://youtu.be/LINK  (update after uploading)\n\n"
    "## Tech Stack\n\n"
    "| Tool | Version | Role |\n"
    "|---|---|---|\n"
    "| Python | 3.11.9 | Runtime |\n"
    "| PyTorch | 2.5.1+cu121 | Deep Learning |\n"
    "| torchvision | 0.20.1 | Pretrained models |\n"
    "| plotnine | 0.15.3 | Grammar of Graphics |\n"
    "| scikit-learn | 1.8.0 | Metrics |\n\n"
    "## License\n\n"
    "MIT\n\n"
    "## Author\n\n"
    "Guillermo Carvajal Vaca\n"
    "MSc Data Science and Applied AI - UCB San Pablo - Santa Cruz de la Sierra, Bolivia\n"
    "https://github.com/guillermocarvajalvaca-dev\n"
)

Path("README.md").write_text(readme, encoding="utf-8")
print("README.md OK")
