from pathlib import Path

readme = (
    "# Landmark Classifier CNN\n\n"
    "![Python 3.11](https://img.shields.io/badge/python-3.11-blue.svg)\n"
    "![PyTorch 2.5](https://img.shields.io/badge/PyTorch-2.5-ee4c2c.svg?logo=pytorch)\n"
    "![License MIT](https://img.shields.io/badge/license-MIT-green.svg)\n\n"
    "> UCB MSc Data Science and AI - Deep Learning Project 5\n"
    "> Guillermo Carvajal Vaca - 2026\n\n"
    "## Overview\n\n"
    "Automatic landmark classification using CNNs in PyTorch.\n"
    "Infers geographic location from images without GPS metadata across 50 landmark classes.\n\n"
    "| Phase | Approach | Target | Result |\n"
    "|---|---|---|---|\n"
    "| Phase 2 | CNN from Scratch (5 conv + BN + GAP) | Test Accuracy >= 40% | 31.84% |\n"
    "| Phase 3 | Transfer Learning (ResNet18 / ResNet50) | Test Accuracy >= 70% | **79.68%** + bonus |\n"
    "| Phase 4 | TorchScript inference app | predict_landmarks(img_path, k) | Done |\n\n"
    "## Dataset\n\n"
    "Subset of Google Landmarks Dataset v2 - 50 classes.\n"
    "Provided by UCB instructor. Not included in this repository.\n\n"
    "Place the dataset at the root of the project directory:\n\n"
    "```\n"
    "./data/landmark_images/\n"
    "    train/  <- one subfolder per class\n"
    "    test/   <- same structure\n"
    "```\n\n"
    "## Installation\n\n"
    "```bash\n"
    "git clone https://github.com/guillermocarvajalvaca-dev/landmark-classifier.git\n"
    "cd landmark-classifier\n"
    "python -m venv .venv\n"
    ".venv/Scripts/Activate.ps1\n"
    "pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121\n"
    "pip install -r requirements.txt\n"
    "python src/config.py\n"
    "```\n\n"
    "Expected output: `DEVICE: cuda | TRAIN_DIR exists=True | TEST_DIR exists=True`\n\n"
    "## Execution\n\n"
    "| Node | Role | Notebooks |\n"
    "|---|---|---|\n"
    "| PyCharm (local) | src/ development, EDA, inference | 01, 04 |\n"
    "| Google Colab Pro A100 | Training (30 epochs scratch / 10 epochs transfer) | 02, 03 |\n\n"
    "Open notebooks from GitHub directly in Colab. Cell 0A mounts Drive and pulls latest src/ automatically.\n\n"
    "## Inference\n\n"
    "```python\n"
    "from src.predictor import predict_landmarks\n\n"
    "predictions = predict_landmarks('my_photo.jpg', k=3)\n"
    "# [('Eiffel_Tower', 0.87), ('Arc_de_Triomphe', 0.09), ('Notre_Dame', 0.04)]\n"
    "```\n\n"
    "## Results\n\n"
    "| Experiment | Type | Backbone | Strategy | Test Accuracy | Top-5 |\n"
    "|---|---|---|---|---|---|\n"
    "| E1_scratch_baseline | CNN Scratch | - | - | 31.84% | 66.40% |\n"
    "| E2_scratch_augmented | CNN Scratch | - | - | 31.52% | - |\n"
    "| E3_scratch_lower_lr | CNN Scratch | - | - | 31.12% | - |\n"
    "| E4_resnet18_frozen | Transfer Learning | ResNet18 | Frozen | 66.00% | - |\n"
    "| E5_resnet18_finetune_layer4 | Transfer Learning | ResNet18 | Finetune layer4 | 75.12% | - |\n"
    "| **E6_resnet50_frozen** | **Transfer Learning** | **ResNet50** | **Frozen** | **79.68%** | **94.00%** |\n\n"
    "Best model: `E6_resnet50_frozen` - 79.68% Top-1 / 94.00% Top-5.\n\n"
    "## Visualization\n\n"
    "BI-grade training curves via plotnine with UCB corporate palette:\n\n"
    "- `#003262` UCB Blue - primary series (Train)\n"
    "- `#FDB515` UCB Gold - optimal checkpoint marker\n"
    "- `#C4820E` UCB Dark Gold - Validation / overfitting onset\n\n"
    "Each experiment generates: narrative PNG + BI confusion matrix (dpi=200) + Executive Report MD.\n\n"
    "## Tech Stack\n\n"
    "| Tool | Version | Role |\n"
    "|---|---|---|\n"
    "| Python | 3.11.9 | Runtime |\n"
    "| PyTorch | 2.5.1+cu121 | Deep Learning framework |\n"
    "| torchvision | 0.20.1 | Pretrained ResNet models |\n"
    "| plotnine | 0.15.3 | Grammar of Graphics visualization |\n"
    "| scikit-learn | 1.8.0 | Metrics and evaluation |\n"
    "| nbformat | 5.x | Programmatic notebook generation |\n\n"
    "## License\n\n"
    "MIT\n\n"
    "## Author\n\n"
    "Guillermo Carvajal Vaca\n"
    "MSc Data Science and Applied AI - UCB San Pablo - Santa Cruz de la Sierra, Bolivia\n"
    "https://github.com/guillermocarvajalvaca-dev\n"
)

Path("README.md").write_text(readme, encoding="utf-8")
print("README.md OK")
